- name: Installation script for all the local goodies
  hosts: localhost

  tasks:
    - name: install jq
      apt:
        name: jq
        update_cache: yes
    - name: install vim
      apt:
        name: vim
    - name: install ssh
      apt:
        name: ssh
        install_recommends: no
    - name: install sudo
      apt:
        name: sudo
        install_recommends: no
    - name: install git
      apt:
        name: git-all
    - name: install ag
      apt:
        name: silversearcher-ag
    - name: Install npm
      apt:
        name: npm
        state: present
        update_cache: yes
