- name: Installation script for all the local goodies
  hosts: localhost

  tasks:
    - name: install jq
      apt:
        name: jq
    - name: install vim
      apt:
        name: vim
    - name: install ssh
      apt:
        name: ssh
        install_recommends: no
    - name: install sudo
      apt:
        name: sudo
        install_recommends: no
    - name: install git
      apt:
        name: git-all
