- name: Installation script for vagrant utilities
  hosts: localhost

  tasks:
    - name: install ssh
      apt:
        name: ssh 
        install_recommends: no

    - name: install sudo
      apt:
        name: sudo 
        install_recommends: no

    - name: create vagrant user
      user:
        name: vagrant
        home: /home/vagrant
        shell: /bin/bash
        password: 'vagrant'
        createhome: yes
        groups:
            - sudo

    - name: add insecure ssh key
      authorized_key:
        user: vagrant
        key: "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ=="
        manage_dir: yes

    - name: literal docker steps hacky mods of the sudoers files
      shell: |
        echo 'vagrant ALL = NOPASSWD: ALL' > /etc/sudoers.d/vagrant
        #sed -i -e 's/\(UsePAM \)yes/\1 no/' /etc/ssh/sshd_config
      args:
        executable: /bin/bash

    - name: everything in the vagrant home should belong to vagrant
      file:
        path: /home/vagrant
        state: directory
        owner: vagrant
        recurse: yes 
        group: vagrant

    - name: mkdir /var/run/ssshd
      file:
        path: /var/run/sshd
        state: directory

    - name: install openssh-client
      apt:
        name: openssh-client
#
